config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :products
  devise_for :users
  resources :charges
  root 'products#index'
  get 'contact', to: 'static_pages#contact'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
   # adds an `image` virtual attribute
  include ImageUploader::Attachment.new(:image)
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if:  :devise_controller?

    protected

      def configure_permitted_parameters

        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :address])

      end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
      def new
      end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

# @customer_obj = customer
  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders =  Order.includes(:product).where(user_id: current_user.id)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    Order.includes(:product).find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    # @order.quantity = 1 # hard-coded for debugging purposes
    # @order.total_amount = @order.quantity * @order.product.price

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Invoice' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit( :user_id, :product_id, :total)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :authenticate_user!
 before_action :set_product, only: [:show, :edit, :update, :destroy]

 # GET /products
 # GET /products.json
  def index
   @products = Product.all
  if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC")
  else
    @products = Product.all.order("created_at DESC")
  end
     end


 # GET /products/1
 # GET /products/1.json
 def show
   @order = Order.new
   @order.product_id = @product.id
   @order.user_id = current_user.id
   @product = Product.includes(:user).find(params[:id])
    end

 # GET /products/new
 def new
   @product = Product.new
 end

 # GET /products/1/edit
 def edit
 end

 # POST /products
 # POST /products.json
 def create
   @product = Product.new(product_params)

   respond_to do |format|
     if @product.save
       format.html { redirect_to @product, notice: 'Product was successfully created.' }
       format.json { render :show, status: :created, location: @product }
     else
       format.html { render :new }
       format.json { render json: @product.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /products/1
 # PATCH/PUT /products/1.json
 def update
   respond_to do |format|
     if @product.update(product_params)
       format.html { redirect_to @product, notice: 'Product was successfully updated.' }
       format.json { render :show, status: :ok, location: @product }
     else
       format.html { render :edit }
       format.json { render json: @product.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /products/1
 # DELETE /products/1.json
 def destroy
   @product.destroy
   respond_to do |format|
     format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_product
     @product = Product.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def product_params
     params.require(:product).permit(:image, :name, :price, :description)
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def contact

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @order_amount %></strong>!</h2>


<%#= @customer_obj.inspect %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <label class="amount">
      <span>Amount: $5</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuyMugs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark">
        <a class="navbar-brand" href="">
         <!-- <%#= image_tag("logo_m.jpg", :class =>"logo") %> -->
        </a>
           <div class="collapse navbar-collapse" id="navbarNav5">
             <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                 <%= link_to('Products', products_path, :class => "nav-link text-white")  %>
               </li>
               <li class="nav-item">
                <%= link_to('Contact', contact_path, :class => "nav-link text-white")  %>
               </li>
               <li class="nav-item">
                <%= form_tag(products_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Products", class: "form-control" %>
                <% end %>
               </li>
             </ul>
             <ul class="navbar-nav justify-content-end ml-auto">
              <li class="nav-item">
               <%#= render 'devise/login_items' %>
              </li>
              <!-- <li class="nav-item">
               <%#= render 'devise/registration_items' %>
              </li> -->
            <!--   <li class="nav-item">
               <%#= render 'devise/registration_items' %>
              </li> -->
              <li class="nav-item">
              <% if user_signed_in? %>
                <div class="dropdown">
                   <button class="btn btn-light dropdown-toggle user-profile ml-5" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-user"></span>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to('Profile', edit_user_registration_path, :class => "nav-link dropdown-item")  %>
                    <%= link_to('Orders', orders_path, :class => "nav-link dropdown-item")  %>
                    <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "nav-link dropdown-item")  %>
                  </div>
                </div>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<!-- <%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, id: :order_total %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :order_user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :order_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> -->

<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :order_quantity %>
  </div> -->
<!-- if hide_fields -->
<!-- displanone div -->
  <div class="field">
<!-- end -->
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :order_user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :order_product_id %>
  </div>
  <!-- if hide_fields -->
</div>
<!-- end -->

  <div class="field">
    <%= form.label :total%>
    <%= form.text_field :total, id: :order_total%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th>User</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.total %></td>
        <td><%= order.user %></td>
        <td><%= order.product %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> -->

<p id="notice"><%= notice %></p>

<p>
 <strong>Total:</strong> <%= @order.total%></p>

 <%= @order.total %>
</p>

<p>
 <strong>User:</strong>
 <%= @order.user %>
</p>

<p>
 <strong>Product:</strong> <%= @order.product.name %></p>
   <img src="<%= @order.product.image_url %>">

</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
 <% if product.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

     <ul>
     <% product.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <section class="fdb-block">
   <div class="container">
     <div class="row justify-content-center">
       <div class="col-12 col-md-8 col-lg-8 col-xl-6">
         <div class="row">
           <div class="col text-center">
             <% if product.id? %>
               <h1>Edit Product</h1>
             <% end %>

             <% unless product.id? %>
               <h1>New Product</h1>
             <% end %>
           </div>
         </div>
         <div class="row align-items-center">
           <div class="col mt-4">
             <label>Product Name</label>
             <%= form.text_field :name, id: :product_name, :class => "form-control", :placeholder => "Product Name" %>
           </div>
         </div>
         <div class="row align-items-center mt-4">
           <div class="col mt-4">
             <label>Description</label>
              <%= form.text_area :description, id: :product_description, :class => "form-control", :placeholder => "Description"%>
           </div>
         </div>

         <div class="row align-items-center mt-4">
           <div class="col mt-4">
             <label>Price</label>
              <%= form.text_field :price, id: :product_price, :class => "form-control", :placeholder => "Price"%>
           </div>
         </div>
         <div class="row align-items-center mt-4">
           <div class="col mt-4">
             <label>Image</label>
               <%= form.file_field :image, id: :product_image%>
           </div>
         </div>

         <div class="row mt-4">
           <div class="col">
             <button class="btn">Submit</button>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>

 <% end %>

app/views/products/_order.html.erb
<%= form_with(model: locals[:order], local: true) do |form| %>
 <% if locals[:order].errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(locals[:order].errors.count, "error") %> prohibited this order from being saved:</h2>

     <ul>
     <% locals[:order].errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>





 <div class="row align-items-center">
   <div class="col">
   <%= form.hidden_field :user_id, id: :order_user_id %>
  </div>
 </div>

 <div class="row align-items-center">
   <div class="col">
    <%= form.hidden_field :product_id, id: :order_product_id %>
   </div>
 </div>

 <div class="row align-items-center">
   <div class="col">
     <%= form.hidden_field :total, id: :order_total %>
   </div>
 </div>

 <div class="row">
   <div class="col">
     <button  class="btn btn-round mt-4 mb-5 mb-md-0", data-toggle="modal" data-target= "#buy_confirm"> Buy</button>
   </div>
 </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<!-- <%#link_to 'log out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %> -->

<h1>Products</h1>

<% @products.each do |product| %>
<div class="card" style="width: 20rem;">
  <%= link_to product_path(product) do %>
    <%= image_tag(product.image_url, class: "card-img-top") %>
  <% end %>
  <div class="card-body">
    <h4 class="card-title"><%= product.name %></h4>
    <h5><%= product.price %></h5>
    <p class="card-text"><%= product.description %></p>
    <%= link_to 'Show', product, class: "btn btn-success" %>
    <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary" %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>
<% end %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Image data:</strong>
  <%= @product.image_data %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> -->

<div class="modal fade" id="buy_confirm" >
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-body">
       <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button> -->
       <!-- <p class="text-success text-center ">Thank you shopping, your order has been successfully placed.</p> -->
     </div>
   </div>
 </div>
</div>

<section class="fdb-block pb-0 pt-5">
   <div class="container">
     <div class="row align-items-center">
       <div class="col-10 col-sm-6 m-auto col-md-4 pb-4 pb-md-0">
         <img src="<%= @product.image_url %>" class="img-fluid br-0">
       </div>
       <div class="col-12 ml-auto col-md-6 col-lg-5">
         <h1><%= @product.name %></h1>
         <p class="text-h3"><%= @product.description %></p>
         <p class="text-h4 text-primary"> $ <%= @product.price %></p>
         <%= render 'order', locals: { product: @product, order: @order } %>


         <!-- stripe form with button -->
         <%= form_tag charges_path do %>
           <article>
             <% if flash[:error].present? %>
               <div id="error_explanation">
                 <p><%= flash[:error] %></p>
               </div>
             <% end %>

             <label class="amount">
               <!-- <span>Amount: $5.00</span> -->
             </label>
           </article>

           <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                   data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                   data-description= <%= @product.name %>
                   data-amount= <%= @product.price * 100 %>
                   data-locale="auto"></script>
         <% end %>



       </div>
     </div>
     <hr>


     <%= link_to 'Back', products_path, :class => 'mt-4' %>
   </div>

</section>

app/views/static_pages/contact.html.erb
<section class="fdb-block">
    <div class="container">
      <div class="row text-center justify-content-center">
        <div class="col-12 col-md-8 col-lg-7">
          <h1>Contact Us</h1>
        </div>
      </div>

     <div class="row pt-4">
        <div class="col-12 col-md-6">
          <iframe class="map"  src="https://www.google.com/maps/embed/v1/place?q=Level+2%2F7+Kelly+St%2C+Ultimo+NSW+2007&zoom=17&key=AIzaSyAcp5poZ0udzV5adwBI8QYCxmF_zJO-bVw"
                width="100%" height="300" frameborder="0" style="border:0" allowfullscreen>
          </iframe>

       </div>

    <form action="https://formspree.io/mail@sanajoshi.com" method="POST">
                <div class="form-group">
                 <!--  <label for="name">Name</label> -->
                  <input type="text" class="form-control" name="name" id="name" placeholder="Name">
                </div>
                <div class="form-group">
                 <!--  <label for="email">Email Address</label> -->
                  <input type="email" class="form-control" name="email" id="email" placeholder="Email Address">
                </div>
                <div class="form-group">
               <!--    <label for="message">Message</label> -->
                  <textarea name="message" cols="40" rows="10" class="form-control" id="message" placeholder="Message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Send Message</button>
              </form>


     </div>
    </div>
  </section>